# Generated by Django 6.1 on 2026-08-11 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorDashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_indicador', models.CharField(max_length=150)),
                ('datos_json', models.JSONField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('periodo_lectivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.periodolectivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
