# Generated by Django 6.1 on 2026-08-11 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0002_initial'),
        ('horarios', '0001_initial'),
        ('laboratorios', '0001_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='bloque_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.bloquehorario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorios.laboratorio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.recursoreservable'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'aprobada'), ('laboratorio__isnull', False)), fields=('laboratorio', 'fecha', 'bloque_horario'), name='unique_reserva_laboratorio_aprobada'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'aprobada'), ('recurso__isnull', False)), fields=('recurso', 'fecha', 'bloque_horario'), name='unique_reserva_recurso_aprobada'),
        ),
    ]
