# Generated by Django 6.1 on 2026-08-11 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('docentes', '0002_initial'),
        ('evaluaciones', '0001_initial'),
        ('seguimiento_academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.paralelo'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.paralelo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='periodo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodolectivo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='tipo_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.evaluacion'),
        ),
        migrations.AddField(
            model_name='indicadoracademico',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='indicadoracademico',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.materia'),
        ),
        migrations.AddField(
            model_name='indicadoracademico',
            name='paralelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.paralelo'),
        ),
        migrations.AddField(
            model_name='indicadoracademico',
            name='periodo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodolectivo'),
        ),
        migrations.AddField(
            model_name='representante',
            name='estudiantes',
            field=models.ManyToManyField(related_name='representantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='representante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
