# Generated by Django 4.2.29 on 2026-08-19 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("seguimiento_academico", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("graduado", "Graduado"),
                            ("retirado", "Retirado"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "paralelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estudiantes",
                        to="academico.paralelo",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudiante_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asistencias",
                to="seguimiento_academico.estudiante",
            ),
        ),
        migrations.AlterField(
            model_name="calificacion",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calificaciones",
                to="seguimiento_academico.estudiante",
            ),
        ),
        migrations.AlterField(
            model_name="representante",
            name="estudiantes",
            field=models.ManyToManyField(
                related_name="representantes", to="seguimiento_academico.estudiante"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asistencia",
            unique_together={("estudiante", "paralelo", "fecha")},
        ),
    ]
