# Generated by Django 6.1 on 2026-08-11 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('docentes', '0001_initial'),
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('es_receso', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.IntegerField()),
                ('estado', models.CharField(choices=[('generado_automatico', 'Generado automático'), ('editado_manual', 'Editado manual'), ('publicado', 'Publicado')], default='generado_automatico', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.bloquehorario')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.docente')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorios.laboratorio')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.paralelo')),
                ('periodo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodolectivo')),
            ],
        ),
        migrations.CreateModel(
            name='ConflictoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_conflicto', models.CharField(choices=[('docente', 'Docente'), ('laboratorio', 'Laboratorio'), ('curso', 'Curso')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('alternativa_propuesta', models.JSONField(blank=True, null=True)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('horario_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.horario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaConsecutivaRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('permitido', models.BooleanField(default=False)),
                ('materia_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecientes_a', to='academico.materia')),
                ('materia_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consecientes_b', to='academico.materia')),
            ],
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('docente', 'dia_semana', 'bloque_horario', 'periodo_lectivo'), name='unique_docente_bloque_periodo'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('laboratorio', 'dia_semana', 'bloque_horario', 'periodo_lectivo'), name='unique_laboratorio_bloque_periodo'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('paralelo', 'dia_semana', 'bloque_horario', 'periodo_lectivo'), name='unique_paralelo_bloque_periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='materiaconsecutivaregla',
            unique_together={('materia_a', 'materia_b')},
        ),
    ]
