# Generated by Django 6.1 on 2026-08-11 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('max_evaluaciones_por_dia', models.IntegerField(default=1)),
                ('periodo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodolectivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('parcial', 'Parcial'), ('final', 'Final'), ('quiz', 'Quiz'), ('proyecto', 'Proyecto')], max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.materia')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.paralelo')),
                ('periodo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodolectivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
