# Generated by Django 4.2.29 on 2026-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materia",
            name="creditos",
            field=models.IntegerField(default=1),
        ),
    ]
