"""
Django settings for Sabrina_Syste project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uu7rmgo-elxd3si^$hw_v7h5=%@xdpx^(t$&bl)ii&xc^6-hth'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

CORS_ALLOW_CREDENTIALS = True

# Allow local and common ngrok domains for development when using ngrok tunnels.
# You can also set a specific host via the NGROK_HOST environment variable
# (e.g. 'abcd-1234-5678.ngrok-free.app' or 'abcd-1234-5678.ngrok.io').
_default_local_hosts = ['localhost', '127.0.0.1', '192.168.1.125']
_ngrok_wildcards = ['.ngrok.io', '.ngrok-free.app', '.ngrok-free.dev']
_env_ngrok_host = os.environ.get('NGROK_HOST')
if _env_ngrok_host:
    # allow an explicit host from environment
    ALLOWED_HOSTS = _default_local_hosts + _ngrok_wildcards + [_env_ngrok_host]
else:
    ALLOWED_HOSTS = _default_local_hosts + _ngrok_wildcards


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'Sabrina_Syste.apps.usuarios',
    'Sabrina_Syste.apps.academico',
    'Sabrina_Syste.apps.docentes',
    'Sabrina_Syste.apps.horarios',
    'Sabrina_Syste.apps.laboratorios',
    'Sabrina_Syste.apps.reservas',
    'Sabrina_Syste.apps.evaluaciones',
    'Sabrina_Syste.apps.seguimiento_academico',
    'Sabrina_Syste.apps.dashboard',
    'Sabrina_Syste.apps.notificaciones',
    'Sabrina_Syste.apps.auditoria',
    'Sabrina_Syste.apps.core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Sabrina_Syste.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sabrina_Syste.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASE_URL = os.environ.get(
    'DATABASE_URL',
    'postgresql://neondb_owner:npg_WtJlShiZr8O3@ep-lucky-cake-ayhy8zxk-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
)
DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'usuarios.Usuario'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'