# Generated by Django 6.1 on 2026-08-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar')], max_length=20)),
                ('modulo', models.CharField(max_length=150)),
                ('objeto_id', models.BigIntegerField()),
                ('detalle', models.JSONField()),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro Auditoría',
                'verbose_name_plural': 'Registros Auditoría',
            },
        ),
        migrations.CreateModel(
            name='RespaldoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=20)),
                ('tamano_mb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
