# Generated by Django 6.1 on 2026-08-11 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('docentes', '0001_initial'),
        ('laboratorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilidaddocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='docentelaboratorioautorizado',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios_autorizados', to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='docentelaboratorioautorizado',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_autorizados', to='laboratorios.laboratorio'),
        ),
        migrations.AddField(
            model_name='docentemateriaautorizada',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_autorizadas', to='docentes.docente'),
        ),
        migrations.AddField(
            model_name='docentemateriaautorizada',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_autorizados', to='academico.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='asignaciondocente',
            unique_together={('docente', 'curso', 'paralelo', 'materia', 'periodo_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='docentelaboratorioautorizado',
            unique_together={('docente', 'laboratorio')},
        ),
        migrations.AlterUniqueTogether(
            name='docentemateriaautorizada',
            unique_together={('docente', 'materia')},
        ),
    ]
